apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fuseki-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: standard  # uncomment and set to match your cluster's StorageClass
