name: SHACL validation

on:
  workflow_call:
  push:
    paths:
      - 'src/ontology/**'
  pull_request:
    paths:
      - 'src/ontology/**'
jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Sync Python environment
        run: uv sync --frozen
      
      - name: Activate uv venv
        run: source .venv/bin/activate


      - name: SHACL validation
        run: |
          uv run python tools/python/checks/shacl.py src/ontology/arema-ontology.ttl src/quality-checks/skohub.shacl.ttl
